
        server:
            port: 8080
        spring:
            datasource:
                url: jdbc:postgresql://localhost:5432/auction_platform
                username: auction_user
                password: password
        